name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # You can adjust this to your Go version
          
      - name: Get dependencies
        run: go mod download
        
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o lattiq-sentinel-linux-amd64 ./cmd/sentinel
          GOOS=linux GOARCH=arm64 go build -v -o lattiq-sentinel-linux-arm64 ./cmd/sentinel
          GOOS=darwin GOARCH=amd64 go build -v -o lattiq-sentinel-darwin-amd64 ./cmd/sentinel
          GOOS=darwin GOARCH=arm64 go build -v -o lattiq-sentinel-darwin-arm64 ./cmd/sentinel
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lattiq-sentinel-linux-amd64
            lattiq-sentinel-linux-arm64
            lattiq-sentinel-darwin-amd64
            lattiq-sentinel-darwin-arm64
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}